config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'videos/top' => 'videos#top'

  devise_for :users
  resources :users, only: [:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :videos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
  resources :photos do
    resources :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create]
  end

  resources :events do
    resources :captures, only: [:create, :destroy]
    resources :opinions, only: [:create]
  end
  root 'videos#top'
end

app/models/capture.rb
class Capture < ApplicationRecord
  self.table_name = "captures"
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  self.table_name = "comments"
  belongs_to :user
  belongs_to :video
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
    self.table_name = "events"
    belongs_to :user

    has_many :captures, dependent: :destroy
    has_many :captured_users, through: :captures, source: :user
    has_many :opinions, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  self.table_name = "favorites"
  belongs_to :photo
  belongs_to :user

  validates_uniqueness_of :photo_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  self.table_name = "likes"
  belongs_to :video
  belongs_to :user

  validates_uniqueness_of :video_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  self.table_name = "messages"
  belongs_to :user
  belongs_to :room
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  self.table_name = "opinions"
  belongs_to :user
  belongs_to :event
end

app/models/photo.rb
class Photo < ApplicationRecord
    self.table_name = "photos"
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user
    has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  self.table_name = "reviews"
  belongs_to :user
  belongs_to :photo
end

app/models/room.rb
class Room < ApplicationRecord
    self.table_name = "rooms"
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "users"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :videos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_videos, through: :likes, source: :video

  has_many :photos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_photos, through: :favorites, source: :photo
  has_many :reviews, dependent: :destroy

  has_many :events, dependent: :destroy
  has_many :captures, dependent: :destroy
  has_many :captured_events, through: :captures, source: :event
  has_many :opinions, dependent: :destroy

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

def already_liked?(video)
  self.likes.exists?(video_id: video.id)
end

def already_favorited?(photo)
  self.favorites.exists?(photo_id: photo.id)
end

def already_captured?(event)
  self.captures.exists?(event_id: event.id)
end

end

app/models/video.rb
class Video < ApplicationRecord
    self.table_name = "videos"
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index

        @videos = Video.all
    end
    def new
        @video = Video.new
    end
    
    def create
        video = Video.new(video_params)

        video.user_id = current_user.id

        if video.save!
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end
    
    def show
       
        @video = Video.find(params[:id])
        @comments = @video.comments
        @comment = Comment.new
    end

    def edit
        @video = Video.find(params[:id])
    end
    def update
        video = Video.find(params[:id])
        if video.update(video_params)
        redirect_to :action => "show", :id => video.id
        else
        redirect_to :action => "new"
        end
    end


    def destroy
        video = Video.find(params[:id])
        video.destroy
        redirect_to action: :index
    end

    private
        def video_params
            params.require(:video).permit(:comment, :youtube_url)
        end
end

app/helpers/captures_helper.rb
module CapturesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
            return youtube_url[17..27]

        else
            return youtube_url[32..42]

        end
    end
end

app/views/videos/edit.html.erb
<%= form_for @video do |f| %>
    <%= f.label :コメント %>
    <%= f.text_field :comment, :size => 140 %> 
    <%= f.submit "編集する" %>
<% end %>

app/views/videos/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>
    <%= link_to "新規投稿へ", new_video_path %>
    <%= link_to "photo一覧へ", photos_path %>
    <%= link_to "event一覧へ", events_path %>
    <% if user_signed_in? %>
        <%= link_to "マイページへ", user_path(current_user.id) %>
    <% end %>
    <div class="videos-container">
        <% @videos.each do |t| %>

            <div class="video">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/>
                    <%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen %>
                </iframe>
            </div>
            <div class="video">
                <%= t.comment %>
            </div>
            <div class="video">
                <%= link_to t.user.name, user_path(t.user.id) %>
            </div>
            <div class="video">
                <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                        <%= link_to video_like_path(id: t.id, video_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to video_likes_path(id: t.id, video_id: t.id), method: :post do %>
                            <i class="far fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% end %>
                <% else %>
                <i class="far fa-heart"></i><%= t.likes.count %>
                <% end %>
            </div>
            <div class="video">
                <%= link_to "詳細へ", video_path(t.id) %>
                <%= link_to "編集する", edit_video_path(t.id) %>
                <%= button_to "削除する", video_path(t.id), method: :delete %>
            </div>
        <% end %>
    </div>

app/views/videos/new.html.erb
<h1>動画投稿ページ</h1>
<h3>新規投稿ページ</h3>
<%= form_for @video do |f| %>
<div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :comment, :size => "30x2" %>
    <%= f.label :youtube %>
    <%= f.text_field :youtube_url, :size => 140 %>
</div>

    <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", videos_path %> 

app/views/videos/show.html.erb
<h1>Idle</h1>
<h3>動画詳細</h3>
<div class="video">
    <p><%= @video.comment %></p>
    <p><%= @video.created_at %></p>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@video.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <% if user_signed_in? %>
        <% if current_user.already_liked?(@video) %>
            <%= link_to video_like_path(@video), method: :delete do %>
                <i class="fas fa-heart"></i><%= @video.likes.count %>
            <% end %>
        <% else %>
            <%= link_to video_likes_path(@video), method: :post do %>
                <i class="far fa-heart"></i><%= @video.likes.count %>
            <% end %>
        <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @video.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_video_path(@video.id) %>
 
</div>


<h2>いいねしたユーザー</h2>
<% @video.liked_users.each do |user| %>
    <li><%= user.email %></li>
<% end %>

<%= link_to 'ユーザーページへ', user_path(@user.id) %> #追加

<div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
        <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
        </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
        <%= form_with(model: [@video, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
        <% end %>
        <% end %>
    <% end %>
</div>

<%= link_to "video一覧に戻る", videos_path %>

app/views/videos/top.html.erb
<div class="loop02">
    <ul class="loop02__box">
        <li class="loop02__item"><a href="#"><%= image_tag '0000326930_OG.JPG', :width => '300', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000136344_OG.JPG', :width => '300', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000136202_OG.JPG', :width => '600', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000135451_OG.JPG' %></a></li>
    </ul>
    <ul class="loop02__box">
        <li class="loop02__item"><a href="#"><%= image_tag '0000326930_OG.JPG', :width => '300', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000136344_OG.JPG', :width => '300', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000136202_OG.JPG', :width => '600', :height => '400' %></a></li>
        <li class="loop02__item"><a href="#"><%= image_tag '0000135451_OG.JPG', :width => '600', :height => '400' %></a></li>
    </ul>
</div>

<div class="item-box">
    <div class="item"><%= link_to "video一覧へ", videos_path %></div>
    <div class="item"><%= link_to "photo一覧へ", photos_path %></div>
    <div class="item"><%= link_to "event一覧へ", events_path %></div>
</div>